In [8]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# create a toy dataset with two features
X = np.array([[1, 2], [3, 4], [5, 6]])


Training data after scaling:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
train mean: 
 [0. 0.]
train standart deviation: 
 [1. 1.]


In [15]:
print("X (original data) mean: \n", np.mean(X, axis = 0))
print("X (original data) standart deviation: \n", np.std(X_train, axis= 0))

X (original data) mean: 
 [3. 4.]
X (original data) standart deviation: 
 [1. 1.]


In [17]:
# create a StandardScaler object
scaler = StandardScaler()

scaler.fit(X)
print("StandartScaler mean: \n", scaler.mean_)

StandartScaler mean: 
 [3. 4.]


In [18]:
# use fit_transform on the training data
X_train = scaler.fit_transform(X)
print("Training data after scaling:\n", X_train)
print("train mean: \n", np.mean(X_train, axis = 0))
print("train standart deviation: \n", np.std(X_train, axis= 0))


Training data after scaling:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
train mean: 
 [0. 0.]
train standart deviation: 
 [1. 1.]


In [19]:
# use transform on the testing data
X_test = np.array([[7, 8], [9, 10], [11, 13]])
X_test_scaled = scaler.transform(X_test)
print("Testing data after scaling:\n", X_test_scaled)
print("test mean: \n", np.mean(X_test, axis = 0))
print("test standart deviation: \n", np.std(X_test, axis= 0))

Testing data after scaling:
 [[2.44948974 2.44948974]
 [3.67423461 3.67423461]
 [4.89897949 5.51135192]]
test mean: 
 [ 9.         10.33333333]
test standart deviation: 
 [1.63299316 2.05480467]


As we can see above, test data mean and standart variation are not [0 0] and [1 1] respectively, like the train data was. This is because the mean and std were computed on the train data. 
So, we only fit StandartScaler on the training data. By doing this, we ensure that our model isn't overfitting to the testing data, and that it's being evaluated only on unseen data.